name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Archive production artifacts
        run: tar -czf my-app.tar.gz -C target demo-0.0.1-SNAPSHOT.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: TestDevOps
          path: TestDevOps.tar.gz